### Crear usuario
POST http://localhost:8080/usuarios/signup
Content-Type: application/json

{
  "username": "juanito",
  "email": "juan@mail.com",
  "password": "1234",
  "name": "Juan",
  "lastName": "El Capo"
}

### Email duplicado (debería dar error)
POST http://localhost:8080/usuarios/signup
Content-Type: application/json

{
  "username": "juanito2",
  "email": "juan@mail.com",
  "password": "1234",
  "name": "Juan",
  "lastName": "El Capo"
}

### Login correcto
POST http://localhost:8080/usuarios/login
Content-Type: application/json

{
  "email": "juan@mail.com",
  "password": "1234"
}

### Login con password incorrecta (deberia dar error)
POST http://localhost:8080/usuarios/login
Content-Type: application/json

{
  "email": "juan@mail.com",
  "password": "4321"
}

### Modificar
PUT http://localhost:8080/usuarios/profile/1
Content-Type: application/json

{
  "username": "juanito_editado"
}

### Listar todos
GET http://localhost:8080/usuarios/list

### Traer por id
GET http://localhost:8080/usuarios/profile/1

### Eliminar
DELETE http://localhost:8080/usuarios/1