
// Aca estan las posibles opciones para marcar al crear una prenda


export const CLOTHING_TYPES = [
    { id: 1, label: "Remera" },
    { id: 2, label: "Vestido" },
    { id: 3, label: "Zapatillas" },
    { id: 4, label: "Zapatos" },
    { id: 5, label: "Camisa" },
    { id: 6, label: "Pantalón" },
    { id: 7, label: "Short" },
    { id: 8, label: "Sombrero" },
    { id: 9, label: "Top" },
    { id: 10, label: "Musculosa" },
    { id: 11, label: "Buzo" },
    { id: 12, label: "Campera" },
    { id: 13, label: "Impermeable" },
    { id: 14, label: "Saco" },
    { id: 15, label: "Taco" },
    { id: 16, label: "Gorra" },
    { id: 17, label: "Bufanda" },
    { id: 18, label: "Medias" },
    { id: 19, label: "Calzas" },
    { id: 20, label: "Malla/Traje de baño" },
    { id: 21, label: "Cinturón" },
    { id: 22, label: "Corbata" },
    { id: 23, label: "Guantes" },
    { id: 24, label: "Lentes de sol" },
    { id: 25, label: "Cartera / Bolso" },
    { id: 26, label: "Mochila" },
    { id: 27, label: "Sandalias" },
    { id: 28, label: "Traje" },
    { id: 29, label: "Reloj" },
    { id: 30, label: "Pulseras" },
    { id: 31, label: "Collares" },
    { id: 32, label: "Anillos" },
    { id: 33, label: "Brazaletes" },
    { id: 34, label: "Aros" },
    { id: 35, label: "Cadenas" }
];

export const COLORS = [
    { id: 1, label: "Blanco" },
    { id: 2, label: "Negro" },
    { id: 3, label: "Gris" },
    { id: 4, label: "Azul" },
    { id: 5, label: "Celeste" },
    { id: 6, label: "Rojo" },
    { id: 7, label: "Bordó" },
    { id: 8, label: "Verde" },
    { id: 9, label: "Amarillo" },
    { id: 10, label: "Naranja" },
    { id: 11, label: "Rosa" },
    { id: 12, label: "Violeta" },
    { id: 13, label: "Marrón" },
    { id: 14, label: "Beige" },
    { id: 15, label: "Dorado" },
    { id: 16, label: "Plateado" },
    { id: 17, label: "Multicolor" },
    { id: 18, label: "Estampado" }
];

export const SIZES = [
    { id: 1, label: "XXS" },
    { id: 2, label: "XS" },
    { id: 3, label: "S" },
    { id: 4, label: "M" },
    { id: 5, label: "L" },
    { id: 6, label: "XL" },
    { id: 7, label: "XXL" },
    { id: 8, label: "XXXL" }
];

export const FITS = [
    { id: 1, label: "Slim Fit" },
    { id: 2, label: "Regular Fit" },
    { id: 3, label: "Relaxed Fit" },
    { id: 4, label: "Oversize" },
    { id: 5, label: "Cropped" },
    { id: 6, label: "Asimétrico" },
    { id: 7, label: "Skinny" },
    { id: 8, label: "Chupín" },
    { id: 9, label: "Recto" },
    { id: 10, label: "Wide Leg" },
    { id: 11, label: "Palazzo" },
    { id: 12, label: "Oxford" },
    { id: 13, label: "Bootcut" },
    { id: 14, label: "Mom" },
    { id: 15, label: "Boyfriend" },
    { id: 16, label: "Cargo" },
    { id: 17, label: "Jogger" },
    { id: 18, label: "Tiro Alto" },
    { id: 19, label: "Tiro Medio" },
    { id: 20, label: "Tiro Bajo" }
];

export const MATERIALS = [
    { id: 1, label: "Algodón" },
    { id: 2, label: "Jean/Denim" },
    { id: 3, label: "Lana" },
    { id: 4, label: "Lino" },
    { id: 5, label: "Seda" },
    { id: 6, label: "Cuero" },
    { id: 7, label: "Cuerina/Eco-cuero" },
    { id: 8, label: "Gamuza" },
    { id: 9, label: "Terciopelo" },
    { id: 10, label: "Satén" },
    { id: 11, label: "Encaje" },
    { id: 12, label: "Tul" },
    { id: 13, label: "Nailon" },
    { id: 14, label: "Poliéster" },
    { id: 15, label: "Elastano/Lycra" },
    { id: 16, label: "Viscosa" },
    { id: 17, label: "Polar" },
    { id: 18, label: "Gabardina" },
    { id: 19, label: "Pana" },
    { id: 20, label: "Microfibra" },
    { id: 21, label: "Piel sintética" },
    { id: 22, label: "Lona" },
    { id: 23, label: "Red" },
    { id: 24, label: "Goma" },
    { id: 25, label: "Plástico" },
    { id: 26, label: "Oro" },
    { id: 27, label: "Plata" },
    { id: 28, label: "Acero quirúrgico" },
    { id: 29, label: "Fantasía" }
];